name: Hugin API Load Testing

on: push
#  schedule:
#    - cron: '*/15 * * * *'

jobs:
  test:
    name: k6 Load Test
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:test1234@0.0.0.0:5432/hugin_api_prod
      SYS_HUGIN_NODE_SERVER: blocksum.org:11898
      API_BASE_PATH: /api/v2

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: hugin_api_prod
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.38.1/k6-v0.38.1-linux-amd64.tar.gz -L | tar xvz --strip-components 1

      - name: Install Packages
        run: |
          npm install

      - name: Start Server
        run: |
          npm start && npx wait-on http://127.0.0.1:3000

      - name: Run k6 Tests
        uses: k6io/action@v0.1
        with:
          filename: tests/k6/loadTest.js
